### ISSUE TITLE
Suggestions: Footer should be inside body /  link to atom feed in head

### ISSUE THREAD

**Issue by louisroyer** [ifreund/website#1]
Hi, I just noticed your `<footer>` section is not inside the `<body>` section. Please consider moving line 1 of `website/layouts/partials/foot.html` to line 10.
https://github.com/ifreund/website/blob/cb4e5ac4bc07ca9a84ad28d878d02e9ed37663da/layouts/partials/foot.html#L1-L9

Also, maybe you could add a link to your rss feed in the `<head>` section like:
- `<link rel="alternate" type="application/rss+xml" title="RSS Feed for Isaac Freund's blog" href="https://isaacfreund.com/blog/feed.xml" />`

This will allow auto-detection of the feed by people like me who use "Awesome RSS" extension.

Thanks for your work on `ext-session-lock-v1` by the way :)

**Comment by ifreund** [comment]
Thanks for the very reasonable suggestions, I've implemented both :)

> Thanks for your work on `ext-session-lock-v1` by the way :)

You're very welcome! I'm quite happy with how it's turned out and with the growing adoption.
